language: node_js
before_script:
- npm install -g gulp mocha
services:
- mongodb
env:
- NODE_ENV=test
node_js:
- '4.1'
deploy:
  provider: elasticbeanstalk
  edge: true
  skip_cleanup: true
  zip-file: 'aws/s3/ebs.zip'
  access_key_id:
    secure: w32KS6ZyZQ9ErRdrbaBjdVFGrJOoFLkDXreZaQS45oMQFsNcNpdgAP458t0yGn/46L0kPu9+iw3/a62gn7QIBASBRqnDjR117r3vkh+WXtVi02ENVUYBmRDBZqhitubNahpb8J1hIdkQkgp6Xu/RsgZWK6kuTc1Rpj0c99lFuzy5y7xU6vjUGVk//Y61CS6WU2/s9j4i6Zgz9o0j0OUWxWP2k6rMO+2r6Buhi1DqdiSs1AF+YDKe0cegXz7vMLQu7zF59FtJpUS2CASNyrg/FNMJO1vp8zeyFI2IGJDossG87cEg6N8zlihQ+mF0woFB9GtbFxBK06YnBSUAGBoO0RiNR77Tl9b8e4rhD93Tb648SDlM3rLUwBSREflB9BDoo1x43jTDUuviXVbla+VlVaQGzOI2DoB4rmoUGNlJnPnpFE09pZ7c52q2Jw8RUQTY8+2I1W3g9/NiB78MH8JY4+HcLo1qCTXucx0vQtAUY18CH0mK9TlC1U90u3lMe/lROoU1KTC8wHrFSikNic2Ul2OAk75uNzuLEWgY1Rbvl2J/k+iPWaXZ7oteRT2IVRIJ93bKPMRFFSNkk+Uhf5XdRN2AkmGCMClQTGBCqLbJoFOs7iwabTo1OPKGdkuRchYV1FAROMRc5+N+Y6sn5uqPiFfMOuDePsvGh3BsPui83L8=
  secret_access_key:
    secure: lI/A315/o8/gCXPjDdf48QqZy8lEUyN8YbzIngj57lietDRJisRyh6273ZVmmxPVdhQV5tkgwySvyL8P0ZggBNYtARtKD/g5qOHVW8spgFLy+0mGc9cm21MOH2XFJnSKg+zZ77RA5RSZ24Hq6lkDMQDjYfndioHyTgG7eeUb1HjV7watagArjJ7i6BP7mlebw/79+HMJoml1n83cOVC73dD1dW9wnGqm1H7nEBvAt9kivmPdVuldTahQGbjtQJR4NlIEAGm+Wvyx7BEGJVTX/p6Oke3JHg+jof8UOqeszZiAdp7QgaitEz04wO9YmjiyCO+jUe5iQ991p3LTgYAIkWVGBAMfilwlHQgF8RUoh+cbE4NmE6RxT+ooRUB5qXrCy9ZNl9E95/knuaAoBpvE0kSTcRlp6K9fscZ+nGVecFCR8trOykWt8aMaAADqsSXY3aa6Hq2Bbf1AVC83zBTAb6vgdSPRxZlUxy6l8tglwK32Bte93mFzsiO4B5S3YyeTDL8u+4/r/c2ZL+2eFbyH2QZhPBshPF2s8EAMnTLeyBhcKoAAq9C+z9UFOHeS+2QyvL5GOG9Csz8sdmXP6MaxL7KFWGuYaOmepbPAEep13yE0IrFRq/nNNpAgJ/wmzQvQamAl4MIINYgSBNKmlcRLE+q5rG9IK72ou+dLzcIBA1I=
  app: lasociale
  bucket_name: elasticbeanstalk-us-west-2-393341108492
  region: us-west-2
  env: lasociale-dev
  on:
    repo: LogicalAddress/LaSociale
    branch: master
notifications:
  slack:
    secure: f9MxTGkAz33Jz1BpeS8IZGl5f331nYrhT7tCE/BnzD5rT14g7OEUYBgMy+mJGsbXzaQIM56eWsf6qS945/a2ovYZjfkCPlw5pt0STVaKrONehVN+bSC0YyIPDWyQdppxKQbrj+uo3LtB4DLpaYZEChs14RD1TcgrFKxS1bau+jP/cdPlWQHqEzIKGDs14IgnhBOqFPrBEdX0kf/SNBw1o7FX8t48BS+DA4hjZzgeFFp8MKubvWyOsxlNqIAstnyMBP6oK7HYex1nMcQFqDATgBYLk+V9FZoo4EIcEWoOGp1AuA2ohJkLb6c+gT3BPNprQbnQxyu3GI3X52MjjcTTRY1lARsc2qAk3BytJXfEj6QpQyjLk/24xeKEsIdGl4GvlQ0/Zp7+ByuC7MTScfyWgvM3RfFrpuw+NNc9GxulCTqMMN5dmp1si+1Pd6uc5gTexKJ2D7we7Fk3NV2ujtJTdr451p00glD0Dm71IX4eVdbwdP+WpJsUx2jyckPk/7zVr4Q7J7IXi4C7iwbpelfHWEb28sG8Ha0pSPPogY/I2hQKZjdJLTiNObn9txuZoJt/GDSX1/Db9GCmoO4AY5CCDXm+CX5FJpzm/39aLnYM8Uu0P2pkQsb3jXH283k5NXLSImN4JRRXitwWQf9OySDGJVEINVGve8IjhDDYaXdOAyQ=

